Presentation/Nop.Web/Models/NhaXeBaoCao/DoanhThuNhanVienLuotModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using FluentValidation.Attributes;
using Nop.Web.Framework;
using Nop.Web.Framework.Mvc;
using System.Collections.Generic;
using System;
using Nop.Core.Domain.Chonves;
using Nop.Core.Domain.NhaXes;

namespace Nop.Web.Models.NhaXeBaoCao
{
    //[Validator(typeof(LoginValidator))]
    public partial class DoanhThuNhanVienLuotModel : BaseNopModel
    {
        public DoanhThuNhanVienLuotModel()
        {
            ListLoai1 = new List<SelectListItem>();
            
            ListQuy = new List<SelectListItem>();
            ListMonth = new List<SelectListItem>();
            ListYear = new List<SelectListItem>();
        }
        [NopResourceDisplayName("ChonVe.NhaXe.HanhTrinh.HanhTrinhId")]
        public int HanhTrinhId { get; set; }
        public int ThangId { get; set; }
        public int NamId { get; set; }
        public int QuyId { get; set; }
        public int Loai1Id { get; set; }
        public string SearchName { get; set; }
        public int SoNhanVien { get; set; }
        public int SoNhan { get; set; }
        public IList<SelectListItem> ListLoai1 { get; set; }
       
        public IList<SelectListItem> ListQuy { get; set; }
        public IList<SelectListItem> ListMonth { get; set; }
        public IList<SelectListItem> ListYear { get; set; }
       
        public NhanVienDateModel[,] DoanhThuLuot { get; set; }
        public List<NhanVienDateModel> ListDTLuot { get; set; }

        public class NhanVienDateModel : BaseNopEntityModel
        {

            
            public int Nhan { get; set; }
            public int soLuot { get; set; }
            public int NhanVienId { get; set; }
            public string TenNhanVien { get; set; }
        }
        public class DateModel : BaseNopEntityModel
        {
            public int nhan { get; set; }

            public int day { get; set; }

            public int month { get; set; }
            public int year { get; set; }
        }
      
    }

    
  
}

Presentation/Nop.Web/Models/NhaXeBaoCao/DoanhThuNhanVienTheoXeModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using FluentValidation.Attributes;
using Nop.Web.Framework;
using Nop.Web.Framework.Mvc;
using System.Collections.Generic;
using System;
using Nop.Core.Domain.Chonves;
using Nop.Core.Domain.NhaXes;
using Nop.Web.Models.NhaXes;

namespace Nop.Web.Models.NhaXeBaoCao
{
    //[Validator(typeof(LoginValidator))]
    public  class DoanhThuNhanVienTheoXeModel : BaseNopModel
    {
        public DoanhThuNhanVienTheoXeModel()
        {
            
        }      
       
        public string BienSoXe { get; set; }
        public string TenLaiXe { get; set; }
        public int TongLuot { get; set; }
        public int SoKhach { get; set; }
        public decimal ThanhTien { get; set; }
        public string TienFomat { get; set; }
       
      
    }

    public  class ListDoanhthuNhanVienXeModel : BaseNopModel
    {
        public ListDoanhthuNhanVienXeModel()
        {
            doanhthus = new List<DoanhThuNhanVienTheoXe>();
        }

        [UIHint("DateNullable")]
        [NopResourceDisplayName("ChonVe.NhaXe.BaoCaoNhaXe.TuNgay")]
        public DateTime TuNgay { get; set; }
        [UIHint("DateNullable")]
        [NopResourceDisplayName("ChonVe.NhaXe.BaoCaoNhaXe.DenNgay")]
        public DateTime DenNgay { get; set; }
         public string SearchName { get; set; }
         public List<DoanhThuNhanVienTheoXe> doanhthus { get; set; }


    }
    public class TKLuotKhachHangModel : BaseNopModel
    {
        public TKLuotKhachHangModel()
        {
            doanhthus = new List<DatVe>();
        }

         [UIHint("DateNullable")]
        [NopResourceDisplayName("ChonVe.NhaXe.BaoCaoNhaXe.TuNgay")]
        public DateTime TuNgay { get; set; }
         [UIHint("DateNullable")]
        [NopResourceDisplayName("ChonVe.NhaXe.BaoCaoNhaXe.DenNgay")]
        public DateTime DenNgay { get; set; }
        public int KhachHangId { get; set; }
        public string DienThoai { get; set; }
        public List<DatVe> doanhthus { get; set; }
        public List<HopDongChuyenModel> hopdongchuyens { get; set; }
        public List<ListDoanhThuTongHop> DoanhThuTongHops { get; set; }
        public int TongSL { get; set; }
        public decimal TongTien { get; set; }

    }
    
    public class ListDoanhThuChiTietModel : BaseNopModel
    {
        public ListDoanhThuChiTietModel()
        {
            ListXe = new List<XeDiTrongNgay>();
        }

       
        [UIHint("DateNullable")]
        [NopResourceDisplayName("Ngày đi")]
        public DateTime NgayDi { get; set; }
        public string SearchName { get; set; }
        public List<XeDiTrongNgay> ListXe { get; set; }
       


    }
   
  
}

Presentation/Nop.Web/Controllers/NhaXeBaoCaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nop.Core;
using Nop.Core.Domain.Catalog;
using Nop.Core.Domain.Common;
using Nop.Core.Domain.Customers;
using Nop.Core.Domain.Forums;
using Nop.Core.Domain.Localization;
using Nop.Core.Domain.Media;
using Nop.Core.Domain.Messages;
using Nop.Core.Domain.Orders;
using Nop.Core.Domain.Tax;
using Nop.Services.Authentication;
using Nop.Services.Authentication.External;
using Nop.Services.Common;
using Nop.Services.Customers;
using Nop.Services.Directory;
using Nop.Services.Helpers;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Media;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Seo;
using Nop.Services.Stores;
using Nop.Services.Tax;
using Nop.Web.Extensions;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Security;
using Nop.Web.Framework.UI.Captcha;
using Nop.Web.Models.Common;
using Nop.Web.Models.Customer;
using WebGrease.Css.Extensions;
using Nop.Web.Models.NhaXes;
using Nop.Core.Data;
using Nop.Services.NhaXes;
using Nop.Core.Caching;
using Nop.Core.Domain.News;
using Nop.Core.Domain.NhaXes;
using Nop.Web.Framework.Kendoui;
using Nop.Web.Framework.Mvc;
using Nop.Services.Chonves;
using Nop.Services.Security;
using Nop.Core.Domain.Security;
using System.Globalization;
using Nop.Services.Catalog;
using Nop.Web.Models.VeXeKhach;
using Nop.Core.Domain.Chonves;
using Nop.Web.Models.NhaXeBaoCao;
using System.IO;
using Nop.Services.ExportImport;


namespace Nop.Web.Controllers
{
    public class NhaXeBaoCaoController : BaseNhaXeController
    {
        #region Khoi Tao
        private readonly IStateProvinceService _stateProvinceService;
        private readonly INhaXeService _nhaxeService;
        private readonly ILocalizationService _localizationService;
        private readonly IWorkContext _workContext;
        private readonly ICustomerService _customerService;
        private readonly IDiaChiService _diachiService;
        private readonly INhanVienService _nhanvienService;
        private readonly IPermissionService _permissionService;
        private readonly IHanhTrinhService _hanhtrinhService;
        private readonly IVeXeService _vexeService;
        private readonly IPriceFormatter _priceFormatter;
        private readonly IPhoiVeService _phoiveService;
        private readonly IPhieuGuiHangService _phieuguihangService;
        private readonly IHangHoaService _hanghoaService;
        private readonly IXeInfoService _xeinfoService;
        private readonly ILimousineBanVeService _limousinebanveService;
        private readonly IExportManager _exportManager;
        private readonly IHopDongChuyenService _hopdongchuyenService;

        public NhaXeBaoCaoController(IStateProvinceService stateProvinceService,
            INhaXeService nhaxeService,
            ILocalizationService localizationService,
            IWorkContext workContext,
            ICustomerService customerService,
            IDiaChiService diachiService,
            INhanVienService nhanvienService,
            IPermissionService permissionService,
            IHanhTrinhService hanhtrinhService,
             IVeXeService vexeService,
            IPriceFormatter priceFormatter,
            IPhoiVeService phoiveService,
            IPhieuGuiHangService phieuguihangService,
            IHangHoaService hanghoaService,
            IXeInfoService xeinfoService,
            ILimousineBanVeService limousinebanveService,
             IExportManager exportManager,
            IHopDongChuyenService hopdongchuyenService
            )
        {
            this._limousinebanveService = limousinebanveService;
            this._hanghoaService = hanghoaService;
            this._phieuguihangService = phieuguihangService;
            this._stateProvinceService = stateProvinceService;
            this._nhaxeService = nhaxeService;
            this._localizationService = localizationService;
            this._workContext = workContext;
            this._customerService = customerService;
            this._diachiService = diachiService;
            this._nhanvienService = nhanvienService;
            this._permissionService = permissionService;
            this._hanhtrinhService = hanhtrinhService;
            this._vexeService = vexeService;
            this._priceFormatter = priceFormatter;
            this._phoiveService = phoiveService;
            this._xeinfoService = xeinfoService;
            this._exportManager = exportManager;
            this._hopdongchuyenService = hopdongchuyenService;

        }
        #endregion
        #region Common
        [NonAction]
        protected virtual void PrepareThongKeItemToModel(ThongKeItem model, ThongKeItem item)
        {
            model.Nhan = item.Nhan;
            model.NhanSapXep = item.NhanSapXep;
            model.ItemId = item.ItemId;
            model.ItemDataDate = item.ItemDataDate;
            model.GiaTri = item.GiaTri;
            model.SoLuong = item.SoLuong;
            model.SoLuongDat = item.SoLuongDat;
            model.SoLuongChuyen = item.SoLuongChuyen;
            model.SoLuongHuy = item.SoLuongHuy;
            model.GiaTri1 = item.GiaTri1;
            model.GiaTri2 = item.GiaTri2;
        }
        [NonAction]
        protected virtual void PrepareListQuy(BaoCaoNhaXeModel model)
        {
            if (DateTime.Now.Month < 4)
                model.QuyId = 1;
            else if (DateTime.Now.Month < 7)
                model.QuyId = 2;
            else if (DateTime.Now.Month < 10)
                model.QuyId = 3;
            else
                model.QuyId = 4;
            model.ListQuy = this.GetCVEnumSelectList<ENBaoCaoQuy>(_localizationService, model.QuyId);
        }

        [NonAction]
        protected virtual void PrepareListNgayThangNam(BaoCaoNhaXeModel model)
        {
            model.ThangId = DateTime.Now.Month;
            model.NamId = DateTime.Now.Year;
            for (int i = 2015; i <= DateTime.Now.Year; i++)
            {
                model.ListYear.Add(new SelectListItem { Text = i.ToString(), Value = i.ToString(), Selected = (i == model.NamId) });
            }
            for (int i = 1; i <= 12; i++)
            {
                model.ListMonth.Add(new SelectListItem { Text = "Tháng " + i.ToString(), Value = i.ToString(), Selected = (i == model.ThangId) });
            }
        }

        [NonAction]
        protected virtual IList<SelectListItem> GetListLoaiThoiGian()
        {
            return this.GetCVEnumSelectList<ENBaoCaoLoaiThoiGian>(_localizationService, 0);
        }

        [NonAction]
        protected virtual IList<SelectListItem> GetListChuKyThoiGian()
        {
            return this.GetCVEnumSelectList<ENBaoCaoChuKyThoiGian>(_localizationService, 0);
        }

        void PrepareListVanPhongModel(BaoCaoNhaXeModel model)
        {
            if (this.isRightAccess(_permissionService, StandardPermissionProvider.CVBaoCao))
            {
                var vanphongs = _nhaxeService.GetAllVanPhongByNhaXeId(_workContext.NhaXeId);
                model.VanPhongs = vanphongs.Select(c => new SelectListItem
                {
                    Text = c.TenVanPhong,
                    Value = c.Id.ToString(),
                }).ToList();
            }
            else
            {
                SelectListItem item = new SelectListItem();
                item.Text = _workContext.CurrentVanPhong.TenVanPhong;
                item.Value = _workContext.CurrentVanPhong.Id.ToString();
                item.Selected = true;
                model.VanPhongs.Add(item);
            }
        }

        void PrepareListXeModel(BaoCaoNhaXeModel model)
        {
            var xevanchuyen = _xeinfoService.GetAllXeVanChuyenByNhaXeId(_workContext.NhaXeId);
            model.Xe = xevanchuyen.Select(c => new SelectListItem
            {
                Text = c.BienSo,
                Value = c.Id.ToString(),
            }).ToList();
        }
        #endregion
        #region bao cao doanh thu

        public ActionResult BaoCaoDoanhThu()
        {
            if (this.CheckNoAccessIntoNhaXe(_workContext, _permissionService, StandardPermissionProvider.CVBaoCao))
                return AccessDeniedView();
            var modeldoanhthu = new BaoCaoNhaXeModel();
            modeldoanhthu.ListLoai1 = GetListChuKyThoiGian();
            PrepareListNgayThangNam(modeldoanhthu);
            var hanhtrinhs = _hanhtrinhService.GetAllHanhTrinhByNhaXeId(_workContext.NhaXeId);
            var hanhtrinhninhbinhids = string.Join(",", _nhaxeService.GetHanhTrinhKhuVucsByKhuvucId((int)ENKhuVuc.NINH_BINH).Select(c => c.HanhTrinhId).ToArray());
            modeldoanhthu.ListLoai2 = new List<SelectListItem>();
            modeldoanhthu.ListLoai2.Add(new SelectListItem
            {
                Value = "",
                Text = "----Tất cả các tuyến----",
                Selected=true
            });
            modeldoanhthu.ListLoai2.Add(new SelectListItem
            {
                Value = hanhtrinhninhbinhids,
                Text = "Các tuyến đi, về từ Ninh Bình"
            });
            foreach(var ht in hanhtrinhs)
            {
                modeldoanhthu.ListLoai2.Add(new SelectListItem
                {
                    Value = ht.Id.ToString(),
                    Text = ht.MoTa
                });
            }
            return View(modeldoanhthu);
        }

        [HttpPost]
        public ActionResult BaoCaoDoanhThu(DataSourceRequest command, BaoCaoNhaXeModel model)
        {
            if (this.CheckNoAccessIntoNhaXe(_workContext, _permissionService, StandardPermissionProvider.CVBaoCao))
                return AccessDeniedView();

            var items = _limousinebanveService.GetBaoCaoDoanhThu(model.ThangId, model.NamId, _workContext.NhaXeId, (ENBaoCaoChuKyThoiGian)model.Loai1Id,model.Loai2Ids);

Presentation/Nop.Web/Views/NhaXeBaoCao/DoanhThuHangNgayBanVe.cshtml
@model BaoCaoNhaXeModel
@using Nop.Web.Models.NhaXes
@using Nop.Core.Domain.NhaXes
@using Nop.Core.Infrastructure
@{
    Layout = "~/Views/Shared/_NhaXeLayout.cshtml";
    var defaultGridPageSize = EngineContext.Current.Resolve<Nop.Core.Domain.Common.AdminAreaSettings>().DefaultGridPageSize;
    var gridPageSizes = EngineContext.Current.Resolve<Nop.Core.Domain.Common.AdminAreaSettings>().GridPageSizes;
}
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Content/chonve/nxmenu/baocaodoanhthu.png")" alt="" />
        @T("ChonVe.NhaXe.DoanhThuTheoXeTheoNgay.Title")
    </div>
</div>

<table style="width:100%">
    <tr>
        <td align="center" width="15%">
            <table class="adminContent">
                <tr>
                    <td class="adminTitle" style="text-align:right">
                        @Html.LabelFor(model => model.TuNgay):
                    </td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.TuNgay)
                    </td>
                </tr>
            </table>
        </td>
        <td align="center" width="15%" id="tabThang">
            <table class="adminContent">
                <tr>
                    <td class="adminTitle" style="text-align:right">
                        @Html.LabelFor(model => model.DenNgay):
                    </td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.DenNgay)

                    </td>
                </tr>
            </table>
        </td>
        <td align="center" width="15%">
            <table class="adminContent">
                <tr>
                    <td class="adminTitle" style="text-align:right">
                        Chọn Xe:
                    </td>
                    <td class="adminData">
                        @Html.DropDownListFor(m => m.XeId, Model.Xe)
                    </td>
                </tr>
            </table>
        </td>
        <td style="text-align:right">
            <input type="button" id="btnSearch" class="k-button" value="@T("Admin.Common.Search")" />
        </td>
    </tr>
</table>
<script>
    $(document).ready(function () {
        $('#btnSearch').click(function () {
            //search
            var grid = $('#DoanhThuXeTheoNgay_grid').data('kendoGrid');
            grid.dataSource.page(1);
            return false;
        });
    });
</script>

<table class="adminContent">
    <tr>
        <td>
            <div id="DoanhThuXeTheoNgay_grid">

            </div>
            <script>
                $(document).ready(function () {
                    $("#DoanhThuXeTheoNgay_grid").kendoGrid({
                        dataSource: {
                            type: "json",
                            transport: {
                                read: {
                                    url: "@Html.Raw(Url.Action("DoanhThuHangNgayBanVe", "NhaXeBaoCao"))",
                                    type: "POST",
                                    dataType: "json",
                                    data: additionalData
                                }
                            },
                            schema: {
                                data: "Data",
                                total: "Total",
                                errors: "Errors"
                            },
                            error: function(e) {
                                display_kendoui_grid_error(e);
                                // Cancel the changes
                                this.cancelChanges();
                            },
                            pageSize: @(defaultGridPageSize),
                            serverPaging: true,
                            serverFiltering: true,
                            serverSorting: true
                        },
                        pageable: {
                            refresh: true,
                            pageSizes: [@(gridPageSizes)],
                            messages: {
                                display: "@T("Nop.Common.KendoGrid.display")", //{0} is the index of the first record on the page, {1} - index of the last record on the page, {2} is the total amount of records
                                empty: "@T("Nop.Common.KendoGrid.Empty")",
                                page: "@T("Nop.Common.KendoGrid.Page")",
                                of: "@T("Nop.Common.KendoGrid.Of")", //{0} is total amount of pages
                                itemsPerPage: "@T("Nop.Common.KendoGrid.itemsPerPage")",
                                first: "@T("Nop.Common.KendoGrid.first")",
                                previous: "@T("Nop.Common.KendoGrid.previous")",
                                next: "@T("Nop.Common.KendoGrid.next")",
                                last: "@T("Nop.Common.KendoGrid.last")",
                                refresh: "@T("Nop.Common.KendoGrid.refresh")"
                            }
                        },
                        editable: {
                            confirmation: false,
                            mode: "inline"
                        },
                        scrollable: false,

                        columns: [
                         
                             {
                                 field: "ThongTinChuyenDi",
                                 title: "Thông Tin Chuyến Đi"
                             },{
                                 field: "NgayBan",
                                 title: "Ngày Đi",
                                 type: "date",
                                 format: "{0:dd/MM/yyyy}"
                             },
                            {
                                field: "TongDoanhThu",
                                title: " Doanh Thu",
                                format: "{0:N0} đ",
                                aggregates: ["sum"]
                            },
                            {
                                field: "Id",
                                title: "@T("Admin.ChonVe.HopDong.ChiTiet")",
                                width: 100,
                                headerAttributes: {
                                    style: "text-align: center;"
                                },
                                attributes: {
                                    style: "text-align: center;"
                                },
                                template: '<a href="javascript:viewdetail(\'#=NgayBan#\')" >@T("Admin.ChonVe.HopDong.ChiTiet")</a>',
                                hidden: false
                            },


                        ]
                    });
                });


                function convert(ngayban) {

                    var date = new Date(ngayban);
                    mnth = ("0" + (date.getMonth() + 1)).slice(-2);
                    day = ("0" + date.getDate()).slice(-2);
                    return [date.getFullYear(), mnth, day].join("-");
                }
                function additionalData() {
                    return {
                        XeId: $("#@Html.FieldIdFor(model => model.XeId)").val(),
                        tuNgay: $("#@Html.FieldIdFor(model => model.TuNgay)").val(),
                        denNgay: $("#@Html.FieldIdFor(model => model.DenNgay)").val(),
                    };
                }
                function detailInit(e) {
                    var xeid = $("#@Html.FieldIdFor(model => model.XeId)").val();
                    var ngayban = e.data.ItemDataDate
                    var adddata = {
                        XeId: xeid,
                        NgayBan: convert(ngayban)
                    };
                }
            </script>

        </td>
    </tr>
</table>
<style>
    .footerTemplateBaoCao {
        text-align: right;
        font-size: 16px;
        color: #1a3410;
    }
</style>
<div id="detailDoanhThuXeTheoNgay_div" style="display:none;">

</div>
<script>
    function viewdetail(ngayban) {
        var _ngayban=convert(ngayban)
        var windowXyLyChuyenVe = $("#detailDoanhThuXeTheoNgay_div");
        if (windowXyLyChuyenVe.data("kendoWindow"))
            windowXyLyChuyenVe.data("kendoWindow").destroy();
        windowXyLyChuyenVe.kendoWindow({
            modal: true,
            width: "700px",
            title: "@T("ChonVe.NhaXe.DoanhThuXeTheoNgay.Title")",
            content: "@(Url.Action("_ChiTietDoanhThuTheoXe", "NhaXeBaoCao"))" + "?NgayBan=" + _ngayban,
            actions: ["Close"]
        });
        windowXyLyChuyenVe.data('kendoWindow').center().open();
    }
</script>

Presentation/Nop.Web/Views/NhaXeBaoCao/DoanhThuLaiXeTheoXe.cshtml
@model ListDoanhthuNhanVienXeModel
@using Nop.Web.Models.NhaXeBaoCao
@using Nop.Core.Domain.NhaXes
@using Nop.Core.Infrastructure
@{
    Layout = "~/Views/Shared/_NhaXeLayout.cshtml";

}
<div class="section-header">
    <div class="title">
        <img src="@Url.Content(" ~ />Content/chonve/nxmenu/baocaodoanhthu.png")" alt="" />
        Doanh thu theo xe và lái xe
    </div>
    <div class="options">
        <input type="button" id="exportdoanhthu" class="k-button" value="Xuất ra excel" />

    </div>
</div>


<table style="width:100%">
    <tr>
        <td align="center" width="15%">
            <table class="adminContent">
                <tr>
                    <td class="adminTitle" style="text-align:right">
                        @Html.LabelFor(model => model.TuNgay):
                    </td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.TuNgay)
                    </td>
                </tr>
            </table>
        </td>
        <td align="center" width="15%" id="tabThang">
            <table class="adminContent">
                <tr>
                    <td class="adminTitle" style="text-align:right">
                        @Html.LabelFor(model => model.DenNgay):
                    </td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.DenNgay)

                    </td>
                </tr>
            </table>
        </td>
        <td align="center" width="15%" id="tabNam">
            <table class="adminContent">
                <tr>
                    <td class="adminTitle" style="text-align:right">
                        Tìm nhân viên:
                    </td>
                    <td class="adminData">
                        @Html.EditorFor(model => model.SearchName)
                    </td>
                </tr>
            </table>
        </td>
        <td style="text-align:right">
            <input type="button" id="btnSearch" class="k-button" value="@T(" admin.common.search")" />
        </td>
    </tr>
</table>
@using (Html.BeginForm("ExportExcelDoanhThuXe", "NhaXeBaoCao", FormMethod.Post, new { id = "export-xml-selected-form" }))
{
    <input type="hidden" id="TuNgay" name="TuNgay" value="" />
    <input type="hidden" id="DenNgay" name="DenNgay" value="" />
    <input type="hidden" id="SearchName" name="SearchName" value="" />
}
<script type="text/javascript">

    $(document).ready(function () {

        $('#exportdoanhthu').click(function () {
            //   e.preventDefault();
            var TuNgay = $("#@Html.FieldIdFor(model => model.TuNgay)").val();
            var DenNgay = $("#@Html.FieldIdFor(model => model.DenNgay)").val();
            var SearchName = $("#@Html.FieldIdFor(model => model.SearchName)").val();

            $('#export-xml-selected-form #TuNgay').val(TuNgay);
            $('#export-xml-selected-form #DenNgay').val(DenNgay);
            $('#export-xml-selected-form #SearchName').val(SearchName);
            $('#export-xml-selected-form').submit();
            return false;
        });
        
    });

</script>

<script>
    $(document).ready(function () {
        $('#btnSearch').click(function () {
            LoadDoanhThuLaiXeTheoXe();
        });
        $('#btnSearch').click();
    });
    function LoadDoanhThuLaiXeTheoXe() {
        var TuNgay = $('#@Html.FieldIdFor(m => m.TuNgay)').val();
        var DenNgay = $('#@Html.FieldIdFor(m => m.DenNgay)').val();
        var SearchName = $('#@Html.FieldIdFor(m => m.SearchName)').val();
        $.ajax({
            cache: false,
            type: "GET",
            dataType: "html",
            contentType: 'application/html;charset=utf-8',
            data: { "TuNgay": TuNgay, "DenNgay": DenNgay, "SearchName": SearchName },
            url: "@(Url.Action("_GetDoanhThuLaiXeTheoXe", "NhaXeBaoCao"))",
            success: function (data) {

                if (data != null) {
                    $("#BangDoanhThuXe").html(data);
                }
                else {
                    $("#BangDoanhThuXe").html("<p>Không có quyền báo vé</p>")
                }

            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert('Chưa đủ thông tin');
            }
        });
    }
</script>
<div id="BangDoanhThuXe" style="overflow-x: scroll; overflow-y: scroll;height:500px">
</div>